package frontend.createframes;

import backend.MainServer;
import frontend.AbstractServerFrame;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Locale;
import java.util.prefs.Preferences;
import java.util.stream.Collectors;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import pojo.College;
import pojo.Programme;
import pojo.Roles;

/**
 *
 * @author Fego
 */
public class CreateStudentFrame extends AbstractServerFrame {

    //Fields
    private MainServer server;
    private String matricNo;
    private String passportFile;
    private Programme progGlobal;
    private String passportFolder;
    private boolean passportSelected = false;
    private Roles role;
    private final String frameRole = "Student";
    private String password;
    private String[] columnNames = new String[]{"Matric No", "Last Name", "First Name"};

    /**
     * Creates new form InsertStudentFrame
     */
    private CreateStudentFrame() {
        initComponents();
    }

    public CreateStudentFrame(MainServer server) {
        this();
        this.server = server;
        initTotalBackgroundDetails(server, true);
        role = rolesFull.stream().filter(role -> role.toString().trim().equalsIgnoreCase(frameRole)).findFirst().orElse(null);
        passportFolder = Preferences.userRoot().node(MainServer.REGISTRYNAME).get("passportUrl", null);
        initPanel(server);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooserPicture = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelInfo = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblReportHeader2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblReportHeader4 = new javax.swing.JLabel();
        lblOriginalFees = new javax.swing.JLabel();
        lblPaidFees = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lblOriginalFees8 = new javax.swing.JLabel();
        lblBalanceFees = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lblOriginalFees5 = new javax.swing.JLabel();
        lblOriginalFees6 = new javax.swing.JLabel();
        lblOriginalFees7 = new javax.swing.JLabel();
        lblReportHeader7 = new javax.swing.JLabel();
        lblPassportEdit = new javax.swing.JLabel();
        lblMatricNoEdit = new javax.swing.JLabel();
        txtTotalUnits = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPaying = new javax.swing.JTextField();
        txtMaxUnits = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtGpa = new javax.swing.JTextField();
        cmbProgramme = new javax.swing.JComboBox<>();
        cmbCollege = new javax.swing.JComboBox<>();
        cmbDept = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnAttach = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        chooserPicture.setDialogTitle("Choose Passport Picture");
        chooserPicture.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        chooserPicture.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Create Student");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelInfo.setBackground(new java.awt.Color(84, 83, 83));

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("GRADE POINT AVERAGE");

        jLabel35.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 204));
        jLabel35.setText("FIRST NAME");

        jLabel36.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("LEVEL");

        jLabel37.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("COLLEGE");

        jLabel38.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 204));
        jLabel38.setText("MATRIC NO");

        jLabel39.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setText("DEPARTMENT");

        jLabel40.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setText("PROGRAMME");

        jLabel41.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("LAST NAME");

        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("TOTAL UNITS REGISTERED");

        lblReportHeader2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader2.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader2.setText("ACADEMIC REPORT");

        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("MAX UNITS ALLOWED");

        lblReportHeader4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader4.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader4.setText("FINANCIAL REPORT");

        lblOriginalFees.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblOriginalFees.setForeground(new java.awt.Color(204, 204, 204));
        lblOriginalFees.setText("N/A");

        lblPaidFees.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblPaidFees.setForeground(new java.awt.Color(204, 204, 204));
        lblPaidFees.setText("N/A");

        jLabel42.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("PAYING");

        lblOriginalFees8.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblOriginalFees8.setForeground(new java.awt.Color(204, 204, 204));
        lblOriginalFees8.setText("N");

        lblBalanceFees.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblBalanceFees.setForeground(new java.awt.Color(204, 204, 204));
        lblBalanceFees.setText("N/A");

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("ORIGINAL SCHOOL FEES");

        jLabel33.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("PAID FEES");

        jLabel34.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("BALANCE FEES");

        lblOriginalFees5.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblOriginalFees5.setForeground(new java.awt.Color(204, 204, 204));
        lblOriginalFees5.setText("N");

        lblOriginalFees6.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblOriginalFees6.setForeground(new java.awt.Color(204, 204, 204));
        lblOriginalFees6.setText("N");

        lblOriginalFees7.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblOriginalFees7.setForeground(new java.awt.Color(204, 204, 204));
        lblOriginalFees7.setText("N");

        lblReportHeader7.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader7.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader7.setText("STUDENT INFORMATION");

        lblPassportEdit.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblPassportEdit.setOpaque(true);
        lblPassportEdit.setPreferredSize(new java.awt.Dimension(147, 140));

        lblMatricNoEdit.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblMatricNoEdit.setForeground(new java.awt.Color(204, 204, 204));
        lblMatricNoEdit.setText("N/A");

        txtTotalUnits.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        txtFirstName.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        txtLastName.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        txtPaying.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        txtMaxUnits.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        txtLevel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        txtGpa.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        cmbProgramme.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cmbProgramme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProgrammeActionPerformed(evt);
            }
        });

        cmbCollege.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cmbCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCollegeActionPerformed(evt);
            }
        });

        cmbDept.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cmbDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDeptActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(204, 204, 204));
        btnCreate.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(204, 204, 204));
        btnCreate.setText("CREATE STUDENT");
        btnCreate.setToolTipText("Add course");
        btnCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreate.setFocusPainted(false);
        btnCreate.setOpaque(false);
        btnCreate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnAttach.setBackground(new java.awt.Color(204, 204, 204));
        btnAttach.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnAttach.setForeground(new java.awt.Color(204, 204, 204));
        btnAttach.setText("ATTACH PASSPORT");
        btnAttach.setToolTipText("Add course");
        btnAttach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAttach.setFocusPainted(false);
        btnAttach.setOpaque(false);
        btnAttach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        btnPay.setBackground(new java.awt.Color(204, 204, 204));
        btnPay.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnPay.setForeground(new java.awt.Color(204, 204, 204));
        btnPay.setText("PAY");
        btnPay.setToolTipText("Add course");
        btnPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPay.setFocusPainted(false);
        btnPay.setOpaque(false);
        btnPay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(82, 82, 82))
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34)
                            .addComponent(jLabel33))
                        .addGap(27, 27, 27)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOriginalFees6)
                                    .addComponent(lblOriginalFees7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblBalanceFees, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(lblPaidFees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPay))
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(lblOriginalFees5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblOriginalFees, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel42)
                                .addGap(35, 35, 35)
                                .addComponent(lblOriginalFees8)
                                .addGap(18, 18, 18)
                                .addComponent(txtPaying, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReportHeader7)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInfoLayout.createSequentialGroup()
                                        .addComponent(lblPassportEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelInfoLayout.createSequentialGroup()
                                                .addComponent(btnAttach)
                                                .addGap(285, 285, 285)
                                                .addComponent(jLabel38))
                                            .addGroup(panelInfoLayout.createSequentialGroup()
                                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel37)
                                                    .addComponent(jLabel39)
                                                    .addComponent(jLabel40))
                                                .addGap(18, 18, 18)
                                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbProgramme, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbDept, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(panelInfoLayout.createSequentialGroup()
                                                        .addComponent(cmbCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel36))))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInfoLayout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(jLabel41)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel35)))
                                .addGap(18, 18, 18)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMatricNoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaxUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblReportHeader4))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblReportHeader2)))
                .addGap(69, 69, 69))
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblReportHeader7)
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel38)
                                .addComponent(lblMatricNoEdit)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(jLabel35)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel36)
                                .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDept, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addGap(18, 18, 18)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbProgramme, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)))
                    .addComponent(lblPassportEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblReportHeader4)
                .addGap(35, 35, 35)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(lblOriginalFees5)
                            .addComponent(lblOriginalFees))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPaidFees)
                                .addComponent(lblOriginalFees6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(lblBalanceFees)
                            .addComponent(lblOriginalFees7)))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPaying, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel42)
                                .addComponent(lblOriginalFees8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblReportHeader2)
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtMaxUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jScrollPane2.setViewportView(panelInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if (confirmAction("Proceed With Student Creation?")) {
            System.out.println("Student creation confirmed");
            if (validateAllFields()) {
                System.out.println("PassportSelected: " + passportSelected);
                System.out.println("Fields validated");
                String loginQuery = String.format("Insert into Login (Username, Password,RoleID) values\n"
                        + "(%d, '%s',%d);",
                        Integer.parseInt(matricNo),
                        password = getPassword(txtFirstName.getText().trim(), txtLastName.getText().trim()),
                        role.getRoleId());

                System.out.println("Login query created: \n" + loginQuery);

                boolean loginInserted = server.sendUpdateQuery(loginQuery);
                System.out.println("Login done: " + loginInserted);

                if (loginInserted) {
                    //get login id
                    String loginIDQuery = "Select LoginID from login where LoginID = (Select Max(LoginID) from login);";

                    int loginID = server.getLoginID(loginIDQuery);
                    System.out.println("LoginID gotten from db: " + loginID);

                    try {
                        String studentQuery = String.format("Insert into Students (MatricNo, Firstname, Lastname, Age, Picture, Level, Gpa, FeeBalance, Student_ProgrammeID, Student_LoginID,"
                                + "Student_MaxUnits, RegistrationAllowed, DeanApproved, HODApproved, CourseAdvisorApproved) Values"
                                + "(%d, '%s' , '%s', %d, '%s', %d, %f, %f, %d, %d,"
                                + " %d, %d, %d, %d, %d);",
                                Integer.parseInt(matricNo),
                                txtFirstName.getText(),
                                txtLastName.getText(),
                                0,
                                (passportFile == null ? "N/A" : passportFile),
                                Integer.parseInt(txtLevel.getText()),
                                Double.parseDouble(txtGpa.getText()),
                                getUnformattedCurrencyValue(lblBalanceFees.getText().trim()),
                                progGlobal.getProgrammeId(),
                                loginID,
                                Integer.parseInt(txtMaxUnits.getText().trim()),
                                0, 0, 0, 0);

                        System.out.println("Student query created: \n" + studentQuery);

                        boolean studentInserted = server.sendUpdateQuery(studentQuery);

                        //refresh the main table
                        //send query to database to update
                        if (studentInserted) {
                            String progQuery = String.format("Update Programmes set StudentsNumber = %d, ProgYearStudentCount = %d where ProgrammeID = %d;",
                                    (progGlobal.getStudentNumber() + 1),
                                    (progGlobal.getStudentYearNumber() + 1),
                                    progGlobal.getProgrammeId());
                            boolean progUpdated = server.sendUpdateQuery(progQuery);
                            if (progUpdated) {
                                displayDefaultPassword(matricNo, password);
                                displayMessage("Student  has been created", "Student Creation Successful");
                                dispose();
                            } else {
                                deletePictureFromPassportFolder(passportSelected, passportFile);
                                deleteCreatedLogin(loginID, server);
                                displayErrorMessage("Error in updating programmes count. Contact admin", "Update Failed");
                            }
                        } else {
                            deletePictureFromPassportFolder(passportSelected, passportFile);
                            deleteCreatedLogin(loginID, server);
                            displayErrorMessage("Error in creating student. Contact admin", "Update Failed");
                        }
                    } catch (Exception ex) {
                        deletePictureFromPassportFolder(passportSelected, passportFile);
                        deleteCreatedLogin(loginID, server);
                        logger.logErrorWithDialog("Error in creating login", ex);
                        System.out.println("Error Logged");
                    }
                } else {
                    deletePictureFromPassportFolder(passportSelected, passportFile);
                    displayErrorMessage("Error in creating login", "Error in update");
                }
            } else {
                displayErrorMessage("A wrong value has been entered into one of the fields. Please check through", "Update Failed");
            }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void cmbCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCollegeActionPerformed
        onChangeSelectedCollege(cmbCollege, cmbDept, true);
        onChangeSelectedDept(cmbDept, cmbProgramme, true);
    }//GEN-LAST:event_cmbCollegeActionPerformed

    private void cmbDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeptActionPerformed
        onChangeSelectedDept(cmbDept, cmbProgramme, true);
    }//GEN-LAST:event_cmbDeptActionPerformed

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        initFileChooser(chooserPicture);
        int open = chooserPicture.showOpenDialog(this);
        System.out.println("Chooser shown");

        if (open == JFileChooser.APPROVE_OPTION) {
            if (passportSelected) {
                deletePictureFromPassportFolder(passportSelected, passportFile);
                passportSelected = true;
            }

            passportFile = initPassport(chooserPicture, lblPassportEdit, passportFolder);
            passportSelected = true;
        } else {
            passportSelected = false;
        }
    }//GEN-LAST:event_btnAttachActionPerformed

    private void cmbProgrammeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProgrammeActionPerformed
        onChangeSelectedProg(cmbProgramme);
    }//GEN-LAST:event_cmbProgrammeActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        if (validateTextNumber(txtPaying)) {
            double paying = getUnformattedCurrencyValue(txtPaying.getText().trim());
            double original = getUnformattedCurrencyValue(lblOriginalFees.getText().trim());
            double balance = original - paying;

            if (paying > original || paying < 0) {
                displayErrorMessage("The amount to be paid is higher than the original fees or negative", "Error updating payment details");
            } else {
                lblPaidFees.setText(getFormattedCurrencyValue(paying));
                lblBalanceFees.setText(getFormattedCurrencyValue(balance));
                txtPaying.setText("");
            }
        } else {
            displayMessage("A letter has been entered in the text field. Only numbers are allowed", "Error in input");
        }

    }//GEN-LAST:event_btnPayActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (confirmAction("End student creation?")) {
            if (passportSelected) {
                deletePictureFromPassportFolder(passportSelected, passportFile);
            }
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    //Custom Methods
    /**
     * Initializes the panel with any pre data before it is shown
     */
    private void initPanel(MainServer server) {
        ArrayList<College> collegeListFull = new ArrayList<>(collegeFull.stream().filter(col -> col.getCollegeDeptNumber() > 0).collect(Collectors.toList()));
        initCombo(cmbCollege, collegeListFull);
        String sessionQuery = String.format("SELECT MaximumUnits FROM sessiondetails \n"
                + "where sessionID = (Select Max(SessionID) from sessiondetails);");

        int maxUnits = Integer.parseInt(String.valueOf(server.getQuerySingleResult(sessionQuery, "MaximumUnits")));
        txtMaxUnits.setText(String.valueOf(maxUnits));
        txtGpa.setText("0");
        txtTotalUnits.setText("0");
        txtLevel.setText("100");
    }

    /**
     * Generates matric no for new student
     *
     * @param prog
     * @return
     */
    private String generateMatricNo(Programme prog) {
        int currentYear = LocalDate.now().getYear();
        String rep = String.valueOf(currentYear);
        String repMain = rep.substring(rep.length() - 2);

        int stuNumber = prog.getStudentYearNumber() + 1;
        int matricType = prog.getMatricType();
        String genMatricTemp = "" + matricType + (stuNumber <= 9 ? "0" + stuNumber : stuNumber);
        String genMatric = genMatricTemp.replace("15", repMain);
        return genMatric;
    }

    /**
     * Validates all necessary filled fields
     *
     * @return
     */
    @Override
    protected boolean validateAllFields() {
        boolean validData = true;

        if (!(fieldHasData(txtFirstName) && validateTextLetter(txtFirstName))) {
            setErrorBorder(txtFirstName, true);
            validData = false;
        } else {
            setErrorBorder(txtFirstName, false);
        }
        if (!(fieldHasData(txtLastName) && validateTextLetter(txtLastName))) {
            setErrorBorder(txtLastName, true);
            validData = false;
        } else {
            setErrorBorder(txtLastName, false);
        }
        if (!(fieldHasData(txtLevel) && validateTextNumber(txtLevel))) {
            setErrorBorder(txtLevel, true);
            validData = false;
        } else {
            setErrorBorder(txtLevel, false);
        }
        if (!(fieldHasData(txtGpa) && validateTextDecimal(txtGpa))) {
            setErrorBorder(txtGpa, true);
            validData = false;
        } else {
            setErrorBorder(txtGpa, false);
        }

        return validData;
    }

    /**
     * When the programme combo changes value initialize the payment label with
     * programme fee
     *
     * @param cmbDept
     * @param cmbProgramme
     */
    private void onChangeSelectedProg(JComboBox<String> cmbProg) {
        if (cmbProg.getSelectedItem() != null) {
            String selected = cmbProg.getSelectedItem().toString();
            Programme progMain = progFull.stream().filter(prog -> prog.toString().trim().equalsIgnoreCase(selected.trim())).findFirst().orElse(null);
            NumberFormat nf = NumberFormat.getInstance(Locale.US);
            lblOriginalFees.setText(String.valueOf(nf.format(progMain.getProgrammeFee())));
            lblPaidFees.setText("0");
            lblBalanceFees.setText("0");
            matricNo = generateMatricNo(progMain);
            lblMatricNoEdit.setText(matricNo);
            progGlobal = progMain;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnPay;
    private javax.swing.JFileChooser chooserPicture;
    private javax.swing.JComboBox<String> cmbCollege;
    private javax.swing.JComboBox<String> cmbDept;
    private javax.swing.JComboBox<String> cmbProgramme;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBalanceFees;
    private javax.swing.JLabel lblMatricNoEdit;
    private javax.swing.JLabel lblOriginalFees;
    private javax.swing.JLabel lblOriginalFees5;
    private javax.swing.JLabel lblOriginalFees6;
    private javax.swing.JLabel lblOriginalFees7;
    private javax.swing.JLabel lblOriginalFees8;
    private javax.swing.JLabel lblPaidFees;
    private javax.swing.JLabel lblPassportEdit;
    private javax.swing.JLabel lblReportHeader2;
    private javax.swing.JLabel lblReportHeader4;
    private javax.swing.JLabel lblReportHeader7;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGpa;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtMaxUnits;
    private javax.swing.JTextField txtPaying;
    private javax.swing.JTextField txtTotalUnits;
    // End of variables declaration//GEN-END:variables
}
