package frontend.createframes;

import backend.MainServer;
import frontend.AbstractServerFrame;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import pojo.College;
import pojo.Staff;

/**
 *
 * @author Fego
 */
public class CreateDeptFrame extends AbstractServerFrame {

    private College collegeGlobal;
    private Staff staffGlobal;

    /**
     * Creates new form CreateDeptFrame
     */
    private CreateDeptFrame() {
        initComponents();
    }

    public CreateDeptFrame(MainServer server) {
        this();
        this.server = server;
        initBackgroundDetailsDept(server, false);
        initPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lblReportHeader7 = new javax.swing.JLabel();
        txtDeptName = new javax.swing.JTextField();
        cmbCollege = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        cmbDeptHead = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Create New Department");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelInfo.setBackground(new java.awt.Color(84, 83, 83));

        jLabel37.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 204));
        jLabel37.setText("DEPARTMENT'S COLLEGE");

        jLabel41.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("DEPARTMENT NAME");

        lblReportHeader7.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader7.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader7.setText("DEPARTMENT INFORMATION");

        txtDeptName.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        cmbCollege.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cmbCollege.setName("CollegeCombo"); // NOI18N
        cmbCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCollegeActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(204, 204, 204));
        btnCreate.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(204, 204, 204));
        btnCreate.setText("CREATE DEPARTMENT");
        btnCreate.setToolTipText("Add course");
        btnCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreate.setFocusPainted(false);
        btnCreate.setOpaque(false);
        btnCreate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        cmbDeptHead.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cmbDeptHead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDeptHeadActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("DEPARTMENT HEAD");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(lblReportHeader7)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCreate))
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel41))
                                .addGap(32, 32, 32)
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbDeptHead, 0, 282, Short.MAX_VALUE)
                                    .addComponent(txtDeptName)
                                    .addComponent(cmbCollege, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(64, 64, 64))))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblReportHeader7)
                .addGap(26, 26, 26)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeptName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(cmbCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDeptHead, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(27, 27, 27)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCollegeActionPerformed
        onChangeSelectedCollege(cmbCollege, cmbDeptHead, staffFull);
    }//GEN-LAST:event_cmbCollegeActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if (confirmAction("Proceed With Department Creation?")) {
            System.out.println("Dept creation confirmed");
            if (validateAllFields()) {

                String deptQuery = String.format("Insert into Departments (DeptName, DeptHead_StaffID, Dept_CollegeID, Dept_StaffNumber, Dept_ProgrammeNumber) values\n"
                        + "('%s', %d, %d, 0, 0);",
                        txtDeptName.getText().trim(),
                        (staffGlobal != null ? staffGlobal.getStaffId() : 0),
                        collegeGlobal.getCollegeId());

                boolean deptInserted = server.sendUpdateQuery(deptQuery);

                if (deptInserted) {
                    String progQuery = String.format("Update Colleges set College_DeptNumber = %d where CollegeID = %d;",
                            (collegeGlobal.getCollegeDeptNumber() + 1),
                            collegeGlobal.getCollegeId());

                    if (server.sendUpdateQuery(progQuery)) {
                        displayMessage("Department  has been created", "Department Creation Successful");
                    } else {
                        deleteLastInsert("Departments", "DeptID", server);
                        displayErrorMessage("Error in updating college department count. Contact admin", "Update Failed");
                    }

                    dispose();
                } else {
                    displayErrorMessage("Error in creating department. Contact admin", "Update Failed");
                    dispose();
                }

            } else {
                displayErrorMessage("A wrong value has been entered into one of the fields. Please check through", "Update Failed");
            }
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void cmbDeptHeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeptHeadActionPerformed
        onChangeSelectedDeptHead(cmbDeptHead);
    }//GEN-LAST:event_cmbDeptHeadActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (confirmAction("End department creation?")) {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    @Override
    protected boolean validateAllFields() {
        boolean validData = true;

        if (!(fieldHasData(txtDeptName) && validateTextLetter(txtDeptName))) {
            setErrorBorder(txtDeptName, true);
            validData = false;
        } else {
            setErrorBorder(txtDeptName, false);
        }

        return validData;
    }

    protected void onChangeSelectedCollege(JComboBox<String> cmbCollege, JComboBox<String> cmbDeptHead, ArrayList<Staff> staffs) {
        //sets the department
        if (cmbCollege.getSelectedItem() != null) {
            String selected = cmbCollege.getSelectedItem().toString().trim();
            System.out.println("Selected Dept: " + selected);
            collegeGlobal = collegeFull.stream().filter(col -> col.toString().trim().equalsIgnoreCase(selected.trim())).findFirst().orElse(null);
            setDeptHeadCombo(cmbDeptHead, collegeGlobal);
        } else {
            System.out.println("Selected Item is null");
        }
    }

    protected void onChangeSelectedDeptHead(JComboBox<String> cmbDeptHead) {
        //sets the department
        if (cmbDeptHead.getSelectedItem() != null) {
            String selected = cmbDeptHead.getSelectedItem().toString().trim();
            System.out.println("Selected Staff: " + selected);
            staffGlobal = staffFull.stream().filter(col -> col.toString().trim().equalsIgnoreCase(selected.trim())).findFirst().orElse(null);
            System.out.println("Selectd Global dept: " + staffGlobal);
        } else {
            System.out.println("Selected Item is null");
        }
    }

    /**
     * Sets the deptHead combo with staffs in that college on change in college
     * selection
     *
     * @param cmbDeptHead
     * @param college
     */
    private void setDeptHeadCombo(JComboBox<String> cmbDeptHead, College college) {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbDeptHead.getModel();
        model.removeAllElements();

        staffFull.stream().
                filter(staff -> deptFull.stream().anyMatch(dept -> dept.getCollegeId() == college.getCollegeId() && staff.getDeptId() == dept.getDeptId()))
                .filter(staff -> staff.getRoleId() == (rolesFull.stream().filter(role -> role.getRoleName().equalsIgnoreCase("HOD")).findFirst().get().getRoleId()))
                .forEach(staff -> model.addElement(staff.toString()));

        cmbDeptHead.setModel(model);

        if (model.getSize() > 0) {
            cmbDeptHead.setSelectedIndex(0);
        }
    }

    private void initPanel() {
        initCombo(cmbCollege, collegeFull);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> cmbCollege;
    private javax.swing.JComboBox<String> cmbDeptHead;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel lblReportHeader7;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JTextField txtDeptName;
    // End of variables declaration//GEN-END:variables

}
