package frontend.viewframes;

import backend.MainServer;
import frontend.AbstractViewFrame;
import frontend.updateframes.UpdateProgrammeFrame;
import java.awt.Point;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import pojo.Department;
import pojo.Programme;

/**
 *
 * @author Fego
 */
public class ViewProgrammeFrame extends AbstractViewFrame {

    private int progID;
    private String[] columnNames = new String[]{"Programme ID", "Programme Name"};
    private String searchText = "";
    private String searchType;

    /**
     * Creates new form ViewProgrammeFrame
     */
    private ViewProgrammeFrame() {
        initComponents();
    }

    public ViewProgrammeFrame(MainServer server) {
        this();
        this.server = server;
        initData(getOtherData(server));
        initTableRecordsProg(tblProg, progList, columnNames);
        for (String col : columnNames) {
            cmbSearch.addItem(col);
        }
        initDocumentListener(txtSearch);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        lblReportHeader7 = new javax.swing.JLabel();
        lblProgName = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lblProgDept = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lblCourseNum = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblMaxLevel = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        lblProgFee = new javax.swing.JLabel();
        lblMatricType = new javax.swing.JLabel();
        lblStuNum = new javax.swing.JLabel();
        lblProgFee1 = new javax.swing.JLabel();
        popStudentOptions = new javax.swing.JPopupMenu();
        itemView = new javax.swing.JMenuItem();
        itemUpdate = new javax.swing.JMenuItem();
        panelMain = new javax.swing.JPanel();
        paneStudents = new javax.swing.JScrollPane();
        tblProg = new javax.swing.JTable();
        setDefaultTableStyle(tblProg);
        tblProg.setFillsViewportHeight(true);
        lblReportHeader5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cmbSearch = new javax.swing.JComboBox<>();

        panelInfo.setBackground(new java.awt.Color(84, 83, 83));
        panelInfo.setPreferredSize(new java.awt.Dimension(563, 430));
        panelInfo.setRequestFocusEnabled(false);

        jLabel41.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("PROGRAMME DEPARTMENT");

        lblReportHeader7.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader7.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader7.setText("DEPARTMENTS INFORMATION");

        lblProgName.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblProgName.setForeground(new java.awt.Color(204, 204, 204));
        lblProgName.setText("N/A");

        jLabel42.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("PROGRAMME NAME");

        lblProgDept.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblProgDept.setForeground(new java.awt.Color(204, 204, 204));
        lblProgDept.setText("N/A");

        jLabel43.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setText("NO OF COURSES");

        lblCourseNum.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblCourseNum.setForeground(new java.awt.Color(204, 204, 204));
        lblCourseNum.setText("N/A");

        jLabel44.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 204, 204));
        jLabel44.setText("PROGRAMME FEE");

        lblMaxLevel.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblMaxLevel.setForeground(new java.awt.Color(204, 204, 204));
        lblMaxLevel.setText("N/A");

        jLabel45.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(204, 204, 204));
        jLabel45.setText("MATRIC NO TYPE");

        jLabel46.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 204, 204));
        jLabel46.setText("MAXIMUM LEVEL FOR PROGRAMME");

        jLabel47.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(204, 204, 204));
        jLabel47.setText("NO OF STUDENTS");

        lblProgFee.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblProgFee.setForeground(new java.awt.Color(204, 204, 204));
        lblProgFee.setText("N/A");

        lblMatricType.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblMatricType.setForeground(new java.awt.Color(204, 204, 204));
        lblMatricType.setText("N/A");

        lblStuNum.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblStuNum.setForeground(new java.awt.Color(204, 204, 204));
        lblStuNum.setText("N/A");

        lblProgFee1.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblProgFee1.setForeground(new java.awt.Color(204, 204, 204));
        lblProgFee1.setText("N");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportHeader7)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel46, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProgName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCourseNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProgDept, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaxLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMatricType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStuNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(lblProgFee1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProgFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblReportHeader7)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblProgName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42)))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgDept)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseNum)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(lblProgFee)
                    .addComponent(lblProgFee1))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(lblMaxLevel))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(lblMatricType))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(lblStuNum))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        popStudentOptions.setRequestFocusEnabled(false);
        popStudentOptions.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                popStudentOptionsFocusLost(evt);
            }
        });

        itemView.setText("View Programmes Details");
        itemView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewActionPerformed(evt);
            }
        });
        popStudentOptions.add(itemView);

        itemUpdate.setText("Update Programme Details");
        itemUpdate.setActionCommand("Update Programme Data");
        itemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUpdateActionPerformed(evt);
            }
        });
        popStudentOptions.add(itemUpdate);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("All Programmes");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });

        panelMain.setBackground(new java.awt.Color(84, 83, 83));
        panelMain.setAutoscrolls(true);

        tblProg.setAutoCreateRowSorter(true);
        tblProg.setBackground(new java.awt.Color(84, 83, 83));
        tblProg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblProg.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        tblProg.setForeground(new java.awt.Color(204, 204, 204));
        tblProg.setToolTipText("List of departments");
        tblProg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblProg.setRowHeight(20);
        tblProg.setRowMargin(3);
        tblProg.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblProg.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblProg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProgMouseClicked(evt);
            }
        });
        paneStudents.setViewportView(tblProg);

        lblReportHeader5.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader5.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader5.setText("PROGRAMMES LIST");

        txtSearch.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("SEARCH");

        cmbSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cmbSearch.setName("CollegeCombo"); // NOI18N
        cmbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                        .addComponent(lblReportHeader5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSearch, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch)
                        .addComponent(jLabel23))
                    .addComponent(lblReportHeader5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewActionPerformed
        initProgFullDataPanel(progID); //initialize fields in the dialog

        JDialog dialogStudent = createDialog(panelInfo, panelInfo.getPreferredSize(), "Programme Details");
        dialogStudent.setAlwaysOnTop(false);
        dialogStudent.addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                popStudentOptions.setVisible(false);
            }

            @Override
            public void windowClosing(WindowEvent e) {
                if (confirmAction("Close full details panel?")) {
                    dialogStudent.dispose();
                }
            }
        });
        dialogStudent.setVisible(true); //Show the dialog
    }//GEN-LAST:event_itemViewActionPerformed

    private void popStudentOptionsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_popStudentOptionsFocusLost
        popStudentOptions.setVisible(false);
    }//GEN-LAST:event_popStudentOptionsFocusLost

    private void tblProgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProgMouseClicked

        if (evt.getClickCount() == 2) {
            Point location = evt.getLocationOnScreen();

            int row = tblProg.getSelectedRow();
            if (row > -1) {
                DefaultTableModel model = (DefaultTableModel) tblProg.getModel();

                progID = Integer.parseInt(String.valueOf(model.getValueAt(row, 0)));
                programme = progList.stream().filter(pr -> pr.getProgrammeId() == progID).findFirst().get();

                popStudentOptions.setLocation(location.x, location.y);
                popStudentOptions.setVisible(true);
            }
        } else {
            popStudentOptions.setVisible(false);
        }
    }//GEN-LAST:event_tblProgMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (confirmAction("Close viewing programmes")) {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void cmbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchActionPerformed
        searchType = cmbSearch.getSelectedItem().toString().trim();
    }//GEN-LAST:event_cmbSearchActionPerformed

    private void itemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUpdateActionPerformed
        new UpdateProgrammeFrame(server, programme).setVisible(true);
        popStudentOptions.setVisible(false);
    }//GEN-LAST:event_itemUpdateActionPerformed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
         popStudentOptions.setVisible(false);
    }//GEN-LAST:event_formWindowIconified

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        popStudentOptions.setVisible(false);
    }//GEN-LAST:event_formWindowLostFocus

    private void initProgFullDataPanel(int progID) {
        Programme prog = progList.stream().filter(pr -> pr.getProgrammeId() == progID).findFirst().get();
        Department dept = deptList.stream().filter(depts -> depts.getDeptId() == prog.getDeptId()).findFirst().get();

        lblProgName.setText(prog.getProgrammeName());
        lblProgFee.setText(String.valueOf(getFormattedCurrencyValue(prog.getProgrammeFee())));
        lblCourseNum.setText(String.valueOf(prog.getProgCourseNumber()));
        lblMatricType.setText(String.valueOf(prog.getMatricType()));
        lblProgDept.setText(dept.getDeptName());
        lblMaxLevel.setText(String.valueOf(prog.getMaximumLevel()));
        lblStuNum.setText(String.valueOf(prog.getStudentNumber()));
    }
    
         
    /**
     * Adds a document listener to the text field for search purposes
     *
     * @param field
     */
    private void initDocumentListener(JTextField field) {
        field.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = field.getText().trim();
                searchText += text.charAt(text.length() - 1);
                searchProgr(tblProg, progList, searchType, searchText, columnNames);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (searchText.length() > 0) {
                    searchText = searchText.substring(0, searchText.length() - 1);
                    searchProgr(tblProg, progList, searchType, searchText, columnNames);
                }
                else{
                    initTableRecordsProg(tblProg, progList, columnNames);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSearch;
    private javax.swing.JMenuItem itemUpdate;
    private javax.swing.JMenuItem itemView;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel lblCourseNum;
    private javax.swing.JLabel lblMatricType;
    private javax.swing.JLabel lblMaxLevel;
    private javax.swing.JLabel lblProgDept;
    private javax.swing.JLabel lblProgFee;
    private javax.swing.JLabel lblProgFee1;
    private javax.swing.JLabel lblProgName;
    private javax.swing.JLabel lblReportHeader5;
    private javax.swing.JLabel lblReportHeader7;
    private javax.swing.JLabel lblStuNum;
    private javax.swing.JScrollPane paneStudents;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPopupMenu popStudentOptions;
    private javax.swing.JTable tblProg;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    protected boolean validateAllFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
