package frontend.viewframes;

import backend.MainServer;
import frontend.AbstractViewFrame;
import frontend.updateframes.UpdateDeptFrame;
import java.awt.Point;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import pojo.Department;

/**
 *
 * @author Fego
 */
public class ViewDepartmentsFrame extends AbstractViewFrame {

    private int deptID;
    private String[] columnNames = new String[]{"Department ID", "Department Name"};
    private String searchText = "";
    private String searchType;

    /**
     * Creates new form ViewDepartments
     */
    private ViewDepartmentsFrame() {
        initComponents();
    }

    public ViewDepartmentsFrame(MainServer server) {
        this();
        this.server = server;
        initData(getOtherData(server));
        initTableRecordsDept(tblDepts, deptList, columnNames);
        for (String col : columnNames) {
            cmbSearch.addItem(col);
        }
        initDocumentListener(txtSearch);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        lblReportHeader7 = new javax.swing.JLabel();
        lblDeptName = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lblDeptHead = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lblProgNum = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblStaffNum = new javax.swing.JLabel();
        popStudentOptions = new javax.swing.JPopupMenu();
        itemView = new javax.swing.JMenuItem();
        itemUpdate = new javax.swing.JMenuItem();
        panelMain = new javax.swing.JPanel();
        paneStudents = new javax.swing.JScrollPane();
        tblDepts = new javax.swing.JTable();
        setDefaultTableStyle(tblDepts);
        tblDepts.setFillsViewportHeight(true);
        lblReportHeader5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cmbSearch = new javax.swing.JComboBox<>();

        panelInfo.setBackground(new java.awt.Color(84, 83, 83));
        panelInfo.setPreferredSize(new java.awt.Dimension(563, 280));

        jLabel41.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("DEPARTMENT HEAD");

        lblReportHeader7.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader7.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader7.setText("DEPARTMENTS INFORMATION");

        lblDeptName.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblDeptName.setForeground(new java.awt.Color(204, 204, 204));
        lblDeptName.setText("N/A");

        jLabel42.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("DEPARTMENT NAME");

        lblDeptHead.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblDeptHead.setForeground(new java.awt.Color(204, 204, 204));
        lblDeptHead.setText("N/A");

        jLabel43.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setText("NO OF PROGRAMMES");

        lblProgNum.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblProgNum.setForeground(new java.awt.Color(204, 204, 204));
        lblProgNum.setText("N/A");

        jLabel44.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 204, 204));
        jLabel44.setText("NO OF STAFFS");

        lblStaffNum.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblStaffNum.setForeground(new java.awt.Color(204, 204, 204));
        lblStaffNum.setText("N/A");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportHeader7)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDeptName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProgNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDeptHead, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStaffNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblReportHeader7)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblDeptName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42)))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeptHead)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgNum)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStaffNum)
                    .addComponent(jLabel44))
                .addGap(31, 31, 31))
        );

        popStudentOptions.setRequestFocusEnabled(false);
        popStudentOptions.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                popStudentOptionsFocusLost(evt);
            }
        });

        itemView.setText("View Departments Details");
        itemView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewActionPerformed(evt);
            }
        });
        popStudentOptions.add(itemView);

        itemUpdate.setText("Update Department Details");
        itemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUpdateActionPerformed(evt);
            }
        });
        popStudentOptions.add(itemUpdate);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("All Departments");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });

        panelMain.setBackground(new java.awt.Color(84, 83, 83));
        panelMain.setAutoscrolls(true);

        tblDepts.setAutoCreateRowSorter(true);
        tblDepts.setBackground(new java.awt.Color(84, 83, 83));
        tblDepts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDepts.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        tblDepts.setForeground(new java.awt.Color(204, 204, 204));
        tblDepts.setToolTipText("List of departments");
        tblDepts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDepts.setRowHeight(20);
        tblDepts.setRowMargin(3);
        tblDepts.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblDepts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDepts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeptsMouseClicked(evt);
            }
        });
        paneStudents.setViewportView(tblDepts);

        lblReportHeader5.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader5.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader5.setText("DEPARTMENTS LIST");

        txtSearch.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("SEARCH");

        cmbSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        cmbSearch.setName("CollegeCombo"); // NOI18N
        cmbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                        .addComponent(lblReportHeader5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSearch, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch)
                        .addComponent(jLabel23))
                    .addComponent(lblReportHeader5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblDeptsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeptsMouseClicked

        if (evt.getClickCount() == 2) {
            Point location = evt.getLocationOnScreen();

            int row = tblDepts.getSelectedRow();
            if (row > -1) {
                DefaultTableModel model = (DefaultTableModel) tblDepts.getModel();

                deptID = Integer.parseInt(String.valueOf(model.getValueAt(row, 0)));

                dept = deptList.stream().
                        filter(dept -> dept.getDeptId() == deptID).
                        findFirst().
                        orElse(null);

                popStudentOptions.setLocation(location.x, location.y);
                popStudentOptions.setVisible(true);
            }
        } else {
            popStudentOptions.setVisible(false);
        }
    }//GEN-LAST:event_tblDeptsMouseClicked

    private void itemViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewActionPerformed
        initDeptFullDataPanel(deptID); //initialize fields in the dialog

        JDialog dialogStudent = createDialog(panelInfo, panelInfo.getPreferredSize(), "Department Details");
        dialogStudent.setAlwaysOnTop(false);
        dialogStudent.addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                popStudentOptions.setVisible(false);
            }

            @Override
            public void windowClosing(WindowEvent e) {
                if (confirmAction("Close full details panel?")) {
                    dialogStudent.dispose();
                }
            }
        });
        dialogStudent.setVisible(true); //Show the dialog
    }//GEN-LAST:event_itemViewActionPerformed

    private void popStudentOptionsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_popStudentOptionsFocusLost
        popStudentOptions.setVisible(false);
    }//GEN-LAST:event_popStudentOptionsFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (confirmAction("Close viewing departments")) {
            popStudentOptions.setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void cmbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchActionPerformed
        searchType = cmbSearch.getSelectedItem().toString().trim();
    }//GEN-LAST:event_cmbSearchActionPerformed

    private void itemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUpdateActionPerformed
        new UpdateDeptFrame(server, dept).setVisible(true);
        popStudentOptions.setVisible(false);
    }//GEN-LAST:event_itemUpdateActionPerformed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        popStudentOptions.setVisible(false);
    }//GEN-LAST:event_formWindowIconified

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        popStudentOptions.setVisible(false);
    }//GEN-LAST:event_formWindowLostFocus

    private void initDeptFullDataPanel(int deptID) {
        deptList.stream().forEach(s -> System.out.println(s.getDeptId()));
        Department dept = deptList.stream().filter(dep -> dep.getDeptId() == deptID).findFirst().get();

        lblDeptName.setText(dept.getDeptName());
        lblProgNum.setText(String.valueOf(dept.getProgNumber()));
        lblDeptHead.setText(getDeptHeadName(dept.getDeptHeadStaffID(), "FullName"));
        lblStaffNum.setText(String.valueOf(dept.getStaffNumber()));
    }

    /**
     * Gets the head of the dept's name
     *
     * @param staffID
     * @return
     */
    private String getDeptHeadName(int staffID, String alias) {
        String query = String.format("Select concat(FirstName, ' ' ,LastName) as %s from staffs where staffID = %d;",
                alias, staffID);
        String name = String.valueOf(server.getQuerySingleResult(query, alias));
        System.out.println("Name: " + name);
        return name.equalsIgnoreCase("0") ? "N/A" : name;
    }

    /**
     * Adds a document listener to the text field for search purposes
     *
     * @param field
     */
    private void initDocumentListener(JTextField field) {
        field.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = field.getText().trim();
                searchText += text.charAt(text.length() - 1);
                searchDept(tblDepts, deptList, searchType, searchText, columnNames);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (searchText.length() > 0) {
                    searchText = searchText.substring(0, searchText.length() - 1);
                    searchDept(tblDepts, deptList, searchType, searchText, columnNames);
                } else {
                    initTableRecordsDept(tblDepts, deptList, columnNames);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSearch;
    private javax.swing.JMenuItem itemUpdate;
    private javax.swing.JMenuItem itemView;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel lblDeptHead;
    private javax.swing.JLabel lblDeptName;
    private javax.swing.JLabel lblProgNum;
    private javax.swing.JLabel lblReportHeader5;
    private javax.swing.JLabel lblReportHeader7;
    private javax.swing.JLabel lblStaffNum;
    private javax.swing.JScrollPane paneStudents;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPopupMenu popStudentOptions;
    private javax.swing.JTable tblDepts;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    protected boolean validateAllFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
