package frontend;

import backend.MainClient;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Fego
 */
public class ClientConfigFrame extends javax.swing.JFrame {

    private final String folderName = "MCU Student Records";
    private ClientConfig config;
    private boolean set;
    private MainClient client;
    protected final static int SELECT = 0, INSERT = 1, UPDATE = 2, DELETE = 3, EXIT= 4, GETINFO = 5;

    /**
     * Creates new form ClientConfigFrame
     *
     * @param set if the config has been sest already then it's in edit mode
     * @param client
     */
    public ClientConfigFrame(boolean set, MainClient client) {
        initComponents();
        config = ClientConfig.getInstance();
        this.client = client;
        
        if (set) {
            initFields();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser = new javax.swing.JFileChooser();
        panelConfig = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblReportHeader4 = new javax.swing.JLabel();
        txtError = new javax.swing.JTextField();
        txtMessage = new javax.swing.JTextField();
        txtPort = new javax.swing.JTextField();
        txtHost = new javax.swing.JTextField();
        btnBrowseError = new javax.swing.JButton();
        btnBrowseLogNormal = new javax.swing.JButton();

        chooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        chooser.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Configure Client Application");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelConfig.setBackground(new java.awt.Color(84, 83, 83));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("ERROR LOGFILE");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("LOG FILES PATH");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("MESSAGE LOGFILE");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("SERVER SETTINGS");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("SERVER PORT");

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("SERVER HOST");

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(204, 204, 204));
        btnSave.setText("SAVE");
        btnSave.setToolTipText("Add course");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setEnabled(false);
        btnSave.setFocusPainted(false);
        btnSave.setOpaque(false);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnEdit.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(204, 204, 204));
        btnEdit.setText("EDIT");
        btnEdit.setToolTipText("Add course");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusPainted(false);
        btnEdit.setOpaque(false);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblReportHeader4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader4.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader4.setText("CONFIGURATION PANEL");

        txtError.setEditable(false);
        txtError.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        txtMessage.setEditable(false);
        txtMessage.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        txtPort.setEditable(false);
        txtPort.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        txtHost.setEditable(false);
        txtHost.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        btnBrowseError.setBackground(new java.awt.Color(204, 204, 204));
        btnBrowseError.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnBrowseError.setForeground(new java.awt.Color(204, 204, 204));
        btnBrowseError.setText("BROWSE");
        btnBrowseError.setToolTipText("Add course");
        btnBrowseError.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrowseError.setEnabled(false);
        btnBrowseError.setFocusPainted(false);
        btnBrowseError.setOpaque(false);
        btnBrowseError.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBrowseError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseErrorActionPerformed(evt);
            }
        });

        btnBrowseLogNormal.setBackground(new java.awt.Color(204, 204, 204));
        btnBrowseLogNormal.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnBrowseLogNormal.setForeground(new java.awt.Color(204, 204, 204));
        btnBrowseLogNormal.setText("BROWSE");
        btnBrowseLogNormal.setToolTipText("Add course");
        btnBrowseLogNormal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrowseLogNormal.setEnabled(false);
        btnBrowseLogNormal.setFocusPainted(false);
        btnBrowseLogNormal.setOpaque(false);
        btnBrowseLogNormal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBrowseLogNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseLogNormalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConfigLayout = new javax.swing.GroupLayout(panelConfig);
        panelConfig.setLayout(panelConfigLayout);
        panelConfigLayout.setHorizontalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigLayout.createSequentialGroup()
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelConfigLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave)
                            .addGroup(panelConfigLayout.createSequentialGroup()
                                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtError, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                                    .addComponent(txtMessage)
                                    .addComponent(txtPort)
                                    .addComponent(txtHost)))))
                    .addGroup(panelConfigLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblReportHeader4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 387, Short.MAX_VALUE)
                        .addComponent(btnEdit)))
                .addGap(18, 18, 18)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBrowseError, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseLogNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        panelConfigLayout.setVerticalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReportHeader4)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfigLayout.createSequentialGroup()
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8))
                    .addGroup(panelConfigLayout.createSequentialGroup()
                        .addComponent(btnBrowseError, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrowseLogNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //Server
        config.setHost(txtHost.getText().trim());
        config.setPort(Integer.parseInt(txtPort.getText().trim()));

        //Log Files
        config.setErrorLog(txtError.getText().trim());
        config.setMessageLog(txtMessage.getText().trim());

        //Store data
        if (config.storeData()) {
            JOptionPane.showMessageDialog(this, "Settings Saved!", "Success", JOptionPane.INFORMATION_MESSAGE);
            int option = JOptionPane.showConfirmDialog(this, "Application needs to be restarted for changes to take place", "Restart Application", JOptionPane.YES_NO_OPTION);

            btnEdit.setEnabled(true);

            if (option == JOptionPane.YES_OPTION) {
                client.sendQueryUTF("exit");
                System.exit(0);
            } else {
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Unable to save, Check backing store or restart application", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        //enable all fields and save button then disable itself
        if (JOptionPane.showConfirmDialog(this, "Do you want to edit these settings?", "Edit", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            enableAllFields();
            btnSave.setEnabled(true);
            btnEdit.setEnabled(false);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBrowseErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseErrorActionPerformed
        browseAndSetUrl(txtError, chooser, "err.txt");
    }//GEN-LAST:event_btnBrowseErrorActionPerformed

    private void btnBrowseLogNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseLogNormalActionPerformed
        browseAndSetUrl(txtMessage, chooser, "msg.txt");
    }//GEN-LAST:event_btnBrowseLogNormalActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int option = JOptionPane.showConfirmDialog(null, "Exit configuration?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * Enables all text fields and password fields for editing
     */
    private void enableAllFields() {
        txtError.setEditable(true);
        txtHost.setEditable(true);
        txtMessage.setEditable(true);
        txtPort.setEditable(true);
        btnBrowseError.setEnabled(true);
        btnBrowseLogNormal.setEnabled(true);
    }

    private void initFields() {
        //Log
        txtError.setText(config.getErrorLog());
        txtMessage.setText(config.getMessageLog());

        //Server
        txtPort.setText(String.valueOf(config.getPort()));
        txtHost.setText(config.getHost());
    }

    /**
     * This sets the url selected in the chooser to the textfield
     *
     * @param field
     * @param chooser
     */
    private void browseAndSetUrl(JTextField field, JFileChooser chooser, String fileName) {
        initFileChooser(chooser);
        int open = chooser.showOpenDialog(this);

        if (open == JFileChooser.APPROVE_OPTION) {
            String directory = chooser.getSelectedFile().getAbsolutePath();

            Path path = Paths.get(directory + "\\" + folderName + "\\" + fileName);
            field.setText(path.toAbsolutePath().toString().trim());
        }
    }

    /**
     * Initializes the JFileChooser with style and dimensions if necessary
     *
     * @param chooser
     */
    private void initFileChooser(JFileChooser chooser) {
        chooser.setCurrentDirectory(Paths.get(System.getenv("ProgramFiles")).getParent().toAbsolutePath().toFile());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseError;
    private javax.swing.JButton btnBrowseLogNormal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JFileChooser chooser;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblReportHeader4;
    private javax.swing.JPanel panelConfig;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
}
