package frontend;

import backend.MainClient;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import pojo.*;

/**
 *
 * @author Fego
 */
public class StudentFrame extends AbstractClientFrame {

    /*
    - Set up the query for inserting data into the registeredCourses table
    - Set up the button listener for register newCourses and remove newCourses
     */
    //Custom Fields
    private MainClient client;
    private final Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    private CardLayout cards;
    private boolean dummy;

    /**
     * Creates new form MainClientFrame
     */
    private StudentFrame() {
        initComponents();
        cards = (CardLayout) panelRegistration.getLayout();
        dummyMode(false);
    }

    public StudentFrame(MainClient client, ArrayList<Object> studentDetails) {
        this();
        this.client = client;
        initDetails(studentDetails);
        initStudentDetailsPanel();
        initAcademicReportPanel();
        initFinancialReportPanel();
        initRegistrationPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseDetails = new javax.swing.JDialog();
        panelCourseDetails = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblCourseCode = new javax.swing.JLabel();
        lblCourseStatus = new javax.swing.JLabel();
        lblCreditUnits = new javax.swing.JLabel();
        lblCourseLevel = new javax.swing.JLabel();
        lblCourseProgramme = new javax.swing.JLabel();
        lblReportHeader5 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        this.setSize(screenSize);
        tabStudent = new javax.swing.JTabbedPane();
        panelInfo = new javax.swing.JPanel();
        lblPassport = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblReportHeader1 = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblDept = new javax.swing.JLabel();
        lblCollege = new javax.swing.JLabel();
        lblProgramme = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblMatricNo = new javax.swing.JLabel();
        panelReport = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblReportHeader = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        lblGpa = new javax.swing.JLabel();
        lblMaxUnits = new javax.swing.JLabel();
        lblRegisteredUnits = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRegistered = new javax.swing.JTable();
        setDefaultTableStyle(tblRegistered);
        tblRegistered.setFillsViewportHeight(true);
        jScrollPane5 = new javax.swing.JScrollPane();
        tblCarried = new javax.swing.JTable();
        setDefaultTableStyle(tblCarried);
        tblCarried.setFillsViewportHeight(true);
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelFinance = new javax.swing.JPanel();
        lblReportHeader3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblOriginalFees = new javax.swing.JLabel();
        lblPaidFees = new javax.swing.JLabel();
        lblBalanceFees = new javax.swing.JLabel();
        lblOriginalFees1 = new javax.swing.JLabel();
        lblOriginalFees2 = new javax.swing.JLabel();
        lblOriginalFees3 = new javax.swing.JLabel();
        panelRegistration = new javax.swing.JPanel();
        panelShowDetails = new javax.swing.JPanel();
        lblReportHeader2 = new javax.swing.JLabel();
        btnShowRegistration = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblRegStatus = new javax.swing.JLabel();
        lblDean = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblCA = new javax.swing.JLabel();
        lblHOD = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblStuReg = new javax.swing.JLabel();
        panelRegister = new javax.swing.JPanel();
        lblReportHeader4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        btnAddNewCourse = new javax.swing.JButton();
        btnAddCarryOver = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSelectedCourses = new javax.swing.JTable();
        setDefaultTableStyle(tblSelectedCourses);
        tblSelectedCourses.setFillsViewportHeight(true);
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNewCourses = new javax.swing.JTable();
        setDefaultTableStyle(tblNewCourses);
        tblNewCourses.setFillsViewportHeight(true);
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCarryOver = new javax.swing.JTable();
        setDefaultTableStyle(tblCarryOver);
        tblCarryOver.setFillsViewportHeight(true);
        btnRemoveCourse = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuChangePassword = new javax.swing.JMenuItem();

        panelCourseDetails.setBackground(new java.awt.Color(84, 83, 83));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("COURSE CODE");

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("CREDIT UNITS");

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("COURSE NAME");

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("LEVEL");

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("COURSE STATUS");

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("PROGRAMME");

        lblCourseName.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblCourseName.setForeground(new java.awt.Color(204, 204, 204));
        lblCourseName.setText("N/A");

        lblCourseCode.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblCourseCode.setForeground(new java.awt.Color(204, 204, 204));
        lblCourseCode.setText("N/A");

        lblCourseStatus.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblCourseStatus.setForeground(new java.awt.Color(204, 204, 204));
        lblCourseStatus.setText("N/A");

        lblCreditUnits.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblCreditUnits.setForeground(new java.awt.Color(204, 204, 204));
        lblCreditUnits.setText("N/A");

        lblCourseLevel.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblCourseLevel.setForeground(new java.awt.Color(204, 204, 204));
        lblCourseLevel.setText("N/A");

        lblCourseProgramme.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblCourseProgramme.setForeground(new java.awt.Color(204, 204, 204));
        lblCourseProgramme.setText("N/A");

        lblReportHeader5.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader5.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader5.setText("COURSE INFO");

        javax.swing.GroupLayout panelCourseDetailsLayout = new javax.swing.GroupLayout(panelCourseDetails);
        panelCourseDetails.setLayout(panelCourseDetailsLayout);
        panelCourseDetailsLayout.setHorizontalGroup(
            panelCourseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCourseDetailsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCourseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCourseDetailsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelCourseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCourseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel12)
                                .addComponent(jLabel14))
                            .addGroup(panelCourseDetailsLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblReportHeader5))))
                    .addGroup(panelCourseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)))
                .addGap(18, 18, 18)
                .addGroup(panelCourseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCourseCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCreditUnits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCourseStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCourseProgramme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCourseLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCourseDetailsLayout.setVerticalGroup(
            panelCourseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCourseDetailsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblReportHeader5)
                .addGap(18, 18, 18)
                .addGroup(panelCourseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCourseCode))
                .addGap(18, 18, 18)
                .addGroup(panelCourseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblCourseName))
                .addGap(18, 18, 18)
                .addGroup(panelCourseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCourseDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(panelCourseDetailsLayout.createSequentialGroup()
                        .addComponent(lblCreditUnits)
                        .addGap(18, 18, 18)
                        .addComponent(lblCourseStatus)))
                .addGap(22, 22, 22)
                .addGroup(panelCourseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCourseDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addGroup(panelCourseDetailsLayout.createSequentialGroup()
                        .addComponent(lblCourseProgramme)
                        .addGap(18, 18, 18)
                        .addComponent(lblCourseLevel)))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout courseDetailsLayout = new javax.swing.GroupLayout(courseDetails.getContentPane());
        courseDetails.getContentPane().setLayout(courseDetailsLayout);
        courseDetailsLayout.setHorizontalGroup(
            courseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCourseDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        courseDetailsLayout.setVerticalGroup(
            courseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCourseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MCU Student Records");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                studentExit(evt);
            }
        });

        tabStudent.setBackground(new java.awt.Color(84, 83, 83));
        tabStudent.setForeground(new java.awt.Color(204, 204, 204));
        tabStudent.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tabStudent.setAutoscrolls(true);
        tabStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabStudent.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N

        panelInfo.setBackground(new java.awt.Color(84, 83, 83));

        lblPassport.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblPassport.setOpaque(true);
        lblPassport.setPreferredSize(new java.awt.Dimension(147, 140));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("FIRST NAME");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("LEVEL");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("COLLEGE");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("MATRIC NO");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("DEPARTMENT");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("PROGRAMME");

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("LAST NAME");

        lblReportHeader1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader1.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader1.setText("STUDENT INFORMATION");

        lblLastName.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(204, 204, 204));
        lblLastName.setText("N/A");

        lblFirstName.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(204, 204, 204));
        lblFirstName.setText("N/A");

        lblDept.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblDept.setForeground(new java.awt.Color(204, 204, 204));
        lblDept.setText("N/A");

        lblCollege.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblCollege.setForeground(new java.awt.Color(204, 204, 204));
        lblCollege.setText("N/A");

        lblProgramme.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblProgramme.setForeground(new java.awt.Color(204, 204, 204));
        lblProgramme.setText("N/A");

        lblLevel.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblLevel.setForeground(new java.awt.Color(204, 204, 204));
        lblLevel.setText("N/A");

        lblMatricNo.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblMatricNo.setForeground(new java.awt.Color(204, 204, 204));
        lblMatricNo.setText("N/A");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportHeader1)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13))
                        .addGap(27, 27, 27)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDept, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(lblCollege, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProgramme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(lblPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatricNo, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                            .addComponent(jLabel5))))
                .addGap(415, 415, 415))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblReportHeader1)
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblMatricNo))
                    .addComponent(lblPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblFirstName))
                .addGap(34, 34, 34)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(jLabel13))
                .addGap(34, 34, 34)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCollege))
                .addGap(34, 34, 34)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblDept))
                .addGap(34, 34, 34)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblProgramme))
                .addGap(34, 34, 34)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblLevel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabStudent.addTab("Student Details", panelInfo);

        panelReport.setBackground(new java.awt.Color(84, 83, 83));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("GRADE POINT AVERAGE");

        lblReportHeader.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader.setText("ACADEMIC REPORT");

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("TOTAL UNITS REGISTERED");

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("MAX UNITS ALLOWED");

        separator.setBackground(new java.awt.Color(153, 153, 153));
        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separator.setOpaque(true);

        lblGpa.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblGpa.setForeground(new java.awt.Color(204, 204, 204));
        lblGpa.setText("N/A");

        lblMaxUnits.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblMaxUnits.setForeground(new java.awt.Color(204, 204, 204));
        lblMaxUnits.setText("N/A");

        lblRegisteredUnits.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblRegisteredUnits.setForeground(new java.awt.Color(204, 204, 204));
        lblRegisteredUnits.setText("N/A");

        tblRegistered.setAutoCreateRowSorter(true);
        tblRegistered.setBackground(new java.awt.Color(84, 83, 83));
        tblRegistered.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblRegistered.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        tblRegistered.setForeground(new java.awt.Color(204, 204, 204));
        tblRegistered.setToolTipText("Courses Registered");
        tblRegistered.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblRegistered.setRowHeight(20);
        tblRegistered.setRowMargin(3);
        tblRegistered.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblRegistered.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblRegistered.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblRegisteredFocusGained(evt);
            }
        });
        tblRegistered.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegisteredMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblRegistered);

        tblCarried.setAutoCreateRowSorter(true);
        tblCarried.setBackground(new java.awt.Color(84, 83, 83));
        tblCarried.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblCarried.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        tblCarried.setForeground(new java.awt.Color(204, 204, 204));
        tblCarried.setToolTipText("Courses Selected For Registration");
        tblCarried.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblCarried.setRowHeight(20);
        tblCarried.setRowMargin(3);
        tblCarried.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblCarried.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCarried.setShowHorizontalLines(false);
        tblCarried.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblCarriedFocusGained(evt);
            }
        });
        tblCarried.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarriedMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblCarried);

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("COURSES REGISTERED");

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("COURSES CARRIED OVER");

        javax.swing.GroupLayout panelReportLayout = new javax.swing.GroupLayout(panelReport);
        panelReport.setLayout(panelReportLayout);
        panelReportLayout.setHorizontalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportHeader)
                    .addGroup(panelReportLayout.createSequentialGroup()
                        .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(38, 38, 38)
                        .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMaxUnits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRegisteredUnits, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addGap(91, 91, 91)
                        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelReportLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel15))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelReportLayout.setVerticalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReportLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblReportHeader)
                .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReportLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblGpa))
                        .addGap(49, 49, 49)
                        .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblMaxUnits))
                        .addGap(49, 49, 49)
                        .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblRegisteredUnits)))
                    .addGroup(panelReportLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19))
                        .addGap(33, 33, 33)
                        .addGroup(panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(panelReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separator))
        );

        tabStudent.addTab("Academic Report", panelReport);

        panelFinance.setBackground(new java.awt.Color(84, 83, 83));

        lblReportHeader3.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader3.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader3.setText("FINANCIAL REPORT");

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("ORIGINAL SCHOOL FEES");

        jLabel27.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("PAID FEES");

        jLabel28.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 204));
        jLabel28.setText("BALANCE FEES");

        lblOriginalFees.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblOriginalFees.setForeground(new java.awt.Color(204, 204, 204));
        lblOriginalFees.setText("N/A");

        lblPaidFees.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblPaidFees.setForeground(new java.awt.Color(204, 204, 204));
        lblPaidFees.setText("N/A");

        lblBalanceFees.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblBalanceFees.setForeground(new java.awt.Color(204, 204, 204));
        lblBalanceFees.setText("N/A");

        lblOriginalFees1.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblOriginalFees1.setForeground(new java.awt.Color(204, 204, 204));
        lblOriginalFees1.setText("N");

        lblOriginalFees2.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblOriginalFees2.setForeground(new java.awt.Color(204, 204, 204));
        lblOriginalFees2.setText("N");

        lblOriginalFees3.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblOriginalFees3.setForeground(new java.awt.Color(204, 204, 204));
        lblOriginalFees3.setText("N");

        javax.swing.GroupLayout panelFinanceLayout = new javax.swing.GroupLayout(panelFinance);
        panelFinance.setLayout(panelFinanceLayout);
        panelFinanceLayout.setHorizontalGroup(
            panelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinanceLayout.createSequentialGroup()
                .addGroup(panelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFinanceLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblReportHeader3))
                    .addGroup(panelFinanceLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(panelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel25)
                            .addComponent(jLabel28))
                        .addGap(48, 48, 48)
                        .addGroup(panelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblOriginalFees1)
                            .addComponent(lblOriginalFees2)
                            .addComponent(lblOriginalFees3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBalanceFees, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPaidFees, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOriginalFees, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(481, Short.MAX_VALUE))
        );
        panelFinanceLayout.setVerticalGroup(
            panelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinanceLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblReportHeader3)
                .addGap(35, 35, 35)
                .addGroup(panelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblOriginalFees)
                    .addComponent(lblOriginalFees1))
                .addGap(37, 37, 37)
                .addGroup(panelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblPaidFees)
                    .addComponent(lblOriginalFees2))
                .addGap(37, 37, 37)
                .addGroup(panelFinanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblBalanceFees)
                    .addComponent(lblOriginalFees3))
                .addContainerGap(302, Short.MAX_VALUE))
        );

        tabStudent.addTab("Financial Report", panelFinance);

        panelRegistration.setBackground(new java.awt.Color(84, 83, 83));
        panelRegistration.setLayout(new java.awt.CardLayout());

        panelShowDetails.setBackground(new java.awt.Color(84, 83, 83));

        lblReportHeader2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader2.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader2.setText("COURSE REGISTRATION");

        btnShowRegistration.setBackground(new java.awt.Color(255, 255, 255));
        btnShowRegistration.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnShowRegistration.setForeground(new java.awt.Color(204, 204, 204));
        btnShowRegistration.setText("REGISTER COURSES");
        btnShowRegistration.setToolTipText("Add course");
        btnShowRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowRegistration.setFocusPainted(false);
        btnShowRegistration.setOpaque(false);
        btnShowRegistration.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnShowRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowRegistrationActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("REGISTRATION STATUS");

        jLabel29.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("HEAD OF DEPARTMENT");

        jLabel30.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("COURSE ADVISOR");

        jLabel31.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("COLLEGE DEAN");

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("ADMIN");

        lblRegStatus.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblRegStatus.setForeground(new java.awt.Color(204, 204, 204));
        lblRegStatus.setText("N/A");

        lblDean.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblDean.setForeground(new java.awt.Color(204, 204, 204));
        lblDean.setText("N/A");

        lblAdmin.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(204, 204, 204));
        lblAdmin.setText("N/A");

        lblCA.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblCA.setForeground(new java.awt.Color(204, 204, 204));
        lblCA.setText("N/A");

        lblHOD.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblHOD.setForeground(new java.awt.Color(204, 204, 204));
        lblHOD.setText("N/A");

        jLabel33.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 204));
        jLabel33.setText("STUDENT REGISTERED");

        lblStuReg.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        lblStuReg.setForeground(new java.awt.Color(204, 204, 204));
        lblStuReg.setText("N/A");

        javax.swing.GroupLayout panelShowDetailsLayout = new javax.swing.GroupLayout(panelShowDetails);
        panelShowDetails.setLayout(panelShowDetailsLayout);
        panelShowDetailsLayout.setHorizontalGroup(
            panelShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowDetailsLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStuReg, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(lblRegStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReportHeader2)
                    .addGroup(panelShowDetailsLayout.createSequentialGroup()
                        .addGroup(panelShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShowRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(157, 157, 157)
                        .addGroup(panelShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel31)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(panelShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCA, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHOD, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDean, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        panelShowDetailsLayout.setVerticalGroup(
            panelShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowDetailsLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblReportHeader2)
                .addGap(40, 40, 40)
                .addGroup(panelShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelShowDetailsLayout.createSequentialGroup()
                        .addGroup(panelShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(lblAdmin))
                        .addGap(18, 18, 18)
                        .addGroup(panelShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(lblCA))
                        .addGap(18, 18, 18)
                        .addGroup(panelShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHOD)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(panelShowDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(lblDean))))
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegStatus)
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(lblStuReg)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        panelRegistration.add(panelShowDetails, "showDetails");

        panelRegister.setBackground(new java.awt.Color(84, 83, 83));
        panelRegister.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N

        lblReportHeader4.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblReportHeader4.setForeground(new java.awt.Color(204, 204, 204));
        lblReportHeader4.setText("REGISTER COURSES");

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("COURSES FOR SEMESTER");

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("COURSES REGISTERED");

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("CARRY OVER COURSES");

        separator1.setBackground(new java.awt.Color(153, 153, 153));
        separator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separator1.setOpaque(true);

        btnAddNewCourse.setBackground(new java.awt.Color(204, 204, 204));
        btnAddNewCourse.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnAddNewCourse.setForeground(new java.awt.Color(204, 204, 204));
        btnAddNewCourse.setText("ADD COURSE");
        btnAddNewCourse.setToolTipText("Add course");
        btnAddNewCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNewCourse.setFocusPainted(false);
        btnAddNewCourse.setOpaque(false);
        btnAddNewCourse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCourseActionPerformed(evt);
            }
        });

        btnAddCarryOver.setBackground(new java.awt.Color(204, 204, 204));
        btnAddCarryOver.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnAddCarryOver.setForeground(new java.awt.Color(204, 204, 204));
        btnAddCarryOver.setText("ADD COURSE");
        btnAddCarryOver.setToolTipText("Add course");
        btnAddCarryOver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCarryOver.setFocusPainted(false);
        btnAddCarryOver.setOpaque(false);
        btnAddCarryOver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddCarryOver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarryOverActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(204, 204, 204));
        btnRegister.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(204, 204, 204));
        btnRegister.setText("REGISTER SELECTED COURSES");
        btnRegister.setToolTipText("Add course");
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.setFocusPainted(false);
        btnRegister.setOpaque(false);
        btnRegister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnQuit.setBackground(new java.awt.Color(204, 204, 204));
        btnQuit.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnQuit.setForeground(new java.awt.Color(204, 204, 204));
        btnQuit.setText("QUIT REGISTRATION");
        btnQuit.setToolTipText("Add course");
        btnQuit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuit.setFocusPainted(false);
        btnQuit.setOpaque(false);
        btnQuit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        tblSelectedCourses.setAutoCreateRowSorter(true);
        tblSelectedCourses.setBackground(new java.awt.Color(84, 83, 83));
        tblSelectedCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblSelectedCourses.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        tblSelectedCourses.setForeground(new java.awt.Color(204, 204, 204));
        tblSelectedCourses.setToolTipText("Courses Selected For Registration");
        tblSelectedCourses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblSelectedCourses.setRowHeight(20);
        tblSelectedCourses.setRowMargin(3);
        tblSelectedCourses.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblSelectedCourses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblSelectedCourses.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblSelectedCoursesFocusGained(evt);
            }
        });
        tblSelectedCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSelectedCoursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSelectedCourses);

        tblNewCourses.setBackground(new java.awt.Color(84, 83, 83));
        tblNewCourses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblNewCourses.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        tblNewCourses.setForeground(new java.awt.Color(204, 204, 204));
        tblNewCourses.setToolTipText("New Semester Courses");
        tblNewCourses.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblNewCourses.setRowHeight(20);
        tblNewCourses.setRowMargin(3);
        tblNewCourses.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblNewCourses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblNewCourses.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblNewCoursesFocusGained(evt);
            }
        });
        tblNewCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNewCoursesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNewCourses);

        tblCarryOver.setAutoCreateRowSorter(true);
        tblCarryOver.setBackground(new java.awt.Color(84, 83, 83));
        tblCarryOver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblCarryOver.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        tblCarryOver.setForeground(new java.awt.Color(204, 204, 204));
        tblCarryOver.setToolTipText("Carry Over Courses");
        tblCarryOver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblCarryOver.setRowHeight(20);
        tblCarryOver.setRowMargin(3);
        tblCarryOver.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tblCarryOver.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCarryOver.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblCarryOverFocusGained(evt);
            }
        });
        tblCarryOver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCarryOverMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCarryOver);

        btnRemoveCourse.setBackground(new java.awt.Color(204, 204, 204));
        btnRemoveCourse.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnRemoveCourse.setForeground(new java.awt.Color(204, 204, 204));
        btnRemoveCourse.setText("REMOVE COURSE");
        btnRemoveCourse.setToolTipText("Add course");
        btnRemoveCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveCourse.setFocusPainted(false);
        btnRemoveCourse.setOpaque(false);
        btnRemoveCourse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemoveCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegisterLayout = new javax.swing.GroupLayout(panelRegister);
        panelRegister.setLayout(panelRegisterLayout);
        panelRegisterLayout.setHorizontalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportHeader4)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnAddNewCourse)))
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterLayout.createSequentialGroup()
                                .addComponent(btnAddCarryOver)
                                .addGap(53, 53, 53))
                            .addComponent(btnQuit, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(43, 43, 43)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnRegister))
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelRegisterLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(56, 56, 56))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnRemoveCourse))))
                .addGap(60, 60, 60))
        );
        panelRegisterLayout.setVerticalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator1)
            .addGroup(panelRegisterLayout.createSequentialGroup()
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRegisterLayout.createSequentialGroup()
                                .addComponent(lblReportHeader4)
                                .addGap(35, 35, 35))
                            .addGroup(panelRegisterLayout.createSequentialGroup()
                                .addComponent(btnQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRemoveCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddNewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCarryOver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panelRegistration.add(panelRegister, "register");

        tabStudent.addTab("Course Registration", panelRegistration);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabStudent)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabStudent)
        );

        jMenu1.setText("File");

        menuChangePassword.setText("Change Password");
        menuChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChangePasswordActionPerformed(evt);
            }
        });
        jMenu1.add(menuChangePassword);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1018, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * What happens when student either logs out or exits the client application
     *
     * @param evt
     */
    private void studentExit(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_studentExit
        if (confirmAction("Do you want to end this session?")) {
            if (dummy) {
                this.dispose();
            } else {
                boolean sent = client.sendQuery(EXIT + ":exit");

                //When staff exits, the login frame becomes visible again
                if (sent) {
                    new ClientLoginFrame().setVisible(true);
                } else {
                    displayErrorMessage("Server may be offline. Contact Server Admin", "Error writing to server");
                }

                this.dispose();
            }
        }
    }//GEN-LAST:event_studentExit

    private void btnShowRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowRegistrationActionPerformed
        if (!dummy) {
            //Check if the student registration is approved by admin and ca
            if (student.isRegistrationAllowed() && student.isCourseAdvisorApproved() && (!student.isRegistrationAllowed())) {
                initTableWithCourses(tblNewCourses, newCourses.getCourseList());
                initTableWithCourses(tblCarryOver, carryOver.getCarriedCourses());
                initSelectedCoursesTable();
                cards.show(panelRegistration, "register");
            } else if (!student.isRegistrationAllowed()) {
                displayErrorMessage("You have not been approved by your admin for registration. Contact Admin", "Cannot Register Courses");
            } else if (!student.isCourseAdvisorApproved()) {
                displayErrorMessage("You have not been approved by your course advisor for registration. Contact Course Advisor", "Cannot Register Courses");
            } else if (student.isDeanApproved()) {
                displayErrorMessage("You have already finished registration. You are not allowed to register again. For updating courses contact admin", "Cannot Register Courses Twice");
            } else if (student.isStuRegistered()) {
                displayErrorMessage("You have already registered your courses. For updating courses contact admin", "Cannot Register Courses Twice");
            }
        }
    }//GEN-LAST:event_btnShowRegistrationActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        if (confirmAction("Do you want to quit course registration?")) {
            cards.show(panelRegistration, "showDetails");
        }
    }//GEN-LAST:event_btnQuitActionPerformed

    //Double clicking on a row in the tables   
    private void tblNewCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNewCoursesMouseClicked
        showCourseInfo(evt, coursesFull);

    }//GEN-LAST:event_tblNewCoursesMouseClicked

    private void tblCarryOverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarryOverMouseClicked
        showCourseInfo(evt, coursesFull);
    }//GEN-LAST:event_tblCarryOverMouseClicked

    private void tblSelectedCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSelectedCoursesMouseClicked
        showCourseInfo(evt, coursesFull);
    }//GEN-LAST:event_tblSelectedCoursesMouseClicked

    //Add buttons action performed
    private void btnAddCarryOverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarryOverActionPerformed
        addCourseRow(tblCarryOver, tblSelectedCourses); //add selected row to selected newCourses table

    }//GEN-LAST:event_btnAddCarryOverActionPerformed

    private void btnAddNewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCourseActionPerformed
        addCourseRow(tblNewCourses, tblSelectedCourses); //add selected row to selected newCourses table

    }//GEN-LAST:event_btnAddNewCourseActionPerformed

    //When tables gain focus
    private void tblNewCoursesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblNewCoursesFocusGained
        loseFocus(tblCarryOver);
        loseFocus(tblSelectedCourses);
    }//GEN-LAST:event_tblNewCoursesFocusGained

    private void tblCarryOverFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblCarryOverFocusGained
        loseFocus(tblNewCourses);
        loseFocus(tblSelectedCourses);

    }//GEN-LAST:event_tblCarryOverFocusGained

    private void tblSelectedCoursesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblSelectedCoursesFocusGained
        loseFocus(tblNewCourses);
        loseFocus(tblCarryOver);
    }//GEN-LAST:event_tblSelectedCoursesFocusGained

    //Remove and register buttons action
    private void btnRemoveCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCourseActionPerformed
        //Remove row from selected newCourses table
        removeCourseRow(tblSelectedCourses);

    }//GEN-LAST:event_btnRemoveCourseActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // Sends a query to insert into the registration table

        //Get data from table
        DefaultTableModel model = (DefaultTableModel) tblSelectedCourses.getModel();
        int rowCount = model.getRowCount();

        //Initial Query to be appended to
        StringBuilder query = new StringBuilder("Insert into RegisteredCourses (Reg_MatricNo, Reg_CourseCode, Reg_SessionID) Values");

        //Get values
        int matricNo = student.getMatricNo();
        int sessionID = session.getSessionId();

        //get course codes
        ArrayList<Course> map = new ArrayList<>();
        ArrayList<String> courseCodes = new ArrayList<>();
        for (int i = 0; i < rowCount; i++) {
            String code = model.getValueAt(i, 0).toString().trim();
            courseCodes.add(code);
            map.add(getCourse(code, coursesFull));
        }

        //Append the values to the original query
        courseCodes.stream().forEach(code -> {
            query.append(String.format("(%d , '%s', %d),", matricNo, code, sessionID));
        });

        int index = query.lastIndexOf(",");
        query.replace(index, query.length(), ";");

        //Send query to server to execute isnert into registeredCourses table
        System.out.println("Query to insert: " + query.toString());
        client.sendQuery(INSERT + ":" + query.toString().trim());

        //wait for response
        boolean inserted = (Boolean) client.getResponse();

        if (inserted) {
            String updateRegStatus = UPDATE + ":Update Students set StudentRegistered = true  where MatricNo = " + student.getMatricNo();
            client.sendQuery(updateRegStatus);

            boolean updated = (Boolean) client.getResponse();
            if (updated) {
                student.setStuRegistered(true);
                lblStuReg.setText("Yes");
                displayMessage("Registration Complete", "Registration Successful");
                initTableWithCourses(tblRegistered, map);
                cards.show(panelRegistration, "showDetails");
            }

        } else {
            displayErrorMessage("Registration failed!, courses may already be registered. Please contact Admin", "Error In Registration");
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void tblRegisteredFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblRegisteredFocusGained
        loseFocus(tblCarried);
    }//GEN-LAST:event_tblRegisteredFocusGained

    private void tblRegisteredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegisteredMouseClicked
        showCourseInfo(evt, coursesFull);
    }//GEN-LAST:event_tblRegisteredMouseClicked

    private void tblCarriedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblCarriedFocusGained
        loseFocus(tblRegistered);
    }//GEN-LAST:event_tblCarriedFocusGained

    private void tblCarriedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarriedMouseClicked
        showCourseInfo(evt, coursesFull);
    }//GEN-LAST:event_tblCarriedMouseClicked

    private void menuChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangePasswordActionPerformed
        JDialog dialog = new JDialog(this);
        JPanel loginPanel = new PanelChangeLogin(client, dialog, "student", student.getMatricNo());
        setDefaultDialogStyle(dialog, loginPanel.getPreferredSize());
        dialog.add(loginPanel);
        dialog.setVisible(true);
        dialog.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
                if (confirmAction("Exit login update")) {
                    dialog.dispose();
                }
            }
        });
    }//GEN-LAST:event_menuChangePasswordActionPerformed

    //Custom Methods
    /**
     * Used to set mode for application running i.e either UI test or actual run
     *
     * @param dummy
     */
    private void dummyMode(boolean dummy) {
        if (dummy) {
            this.dummy = true;
            btnRegister.setEnabled(false);
        } else {
            this.dummy = false;
        }
    }

    /**
     * Shows the full course information in a dialog
     *
     * @param evt Event generated from double clicking
     */
    private void showCourseInfo(MouseEvent evt, ArrayList<Course> courseList) {
        JTable table = (JTable) evt.getSource();

        if (evt.getClickCount() == 2) {
            if (!dummy) {
                int row = table.getSelectedRow();

                if (row > -1) {
                    String courseCode = table.getModel().getValueAt(row, 0).toString(); //get coursecode
                    System.out.println("Course selected: " + courseCode);
                    courseList.stream().forEach(s -> System.out.println("Course: " + s.getCourseCode()));
                    System.out.println("Course list size: " + courseList.size());
                    Course courseIn = courseList.stream().
                            filter(course -> course.getCourseCode().equalsIgnoreCase(courseCode))
                            .findFirst().orElse(null);

                    //create dialog
                    JDialog dialog = createDialog(panelCourseDetails, showCourseInfoSize);
                    initCourseInfo(courseIn); //set dialog details
                    dialog.setVisible(true);

                } else {
                    JDialog dialog = createDialog(panelCourseDetails, showCourseInfoSize);
                    initCourseInfoDummy();
                    dialog.setVisible(true);
                }
            } else {
                table.clearSelection();
            }
        }
    }

    /**
     * Getting student data and de-serializing them into appropriate POJO
     * objects
     *
     * @param data
     */
    private void initDetails(ArrayList<Object> data) {
        for (Object details : data) {
            if (details instanceof Student) {
                student = (Student) details;
            } else if (details instanceof College) {
                college = (College) details;
            } else if (details instanceof Programme) {
                programme = (Programme) details;
            } else if (details instanceof Department) {
                dept = (Department) details;
            } else if (details instanceof CarryOvers) {
                carryOver = (CarryOvers) details;
            } else if (details instanceof RegisteredCourses) {
                regCourses = (RegisteredCourses) details;
            } else if (details instanceof SessionDetails) {
                session = (SessionDetails) details;
            } else if (details instanceof Course) {
                newCourses = (Course) details;
            }
        }

        initSchoolInfo(client);
    }

    /**
     * Initializing the various panels with data gotten from server
     */
    private void initStudentDetailsPanel() {
        lblMatricNo.setText(checkNull(student.getMatricNo()));
        lblFirstName.setText(checkNull(student.getFirstName()));
        lblLastName.setText(checkNull(student.getLastName()));
        lblCollege.setText(checkNull(college.getCollegeName()));
        lblDept.setText(checkNull(dept.getDeptName()));
        lblProgramme.setText(checkNull(programme.getProgrammeName()));
        lblLevel.setText(checkNull(student.getLevel()));
        setLabelImage(student.getPassport(), lblPassport);
    }

    private void initFinancialReportPanel() {
        NumberFormat form = NumberFormat.getInstance(Locale.US);
        lblOriginalFees.setText(checkNull(form.format(programme.getProgrammeFee())));
        lblPaidFees.setText(checkNull(form.format(programme.getProgrammeFee() - student.getFeeBalance())));
        lblBalanceFees.setText(checkNull(form.format(student.getFeeBalance())));
    }

    private void initAcademicReportPanel() {
        lblGpa.setText(checkNull(student.getGpa()));
        lblMaxUnits.setText(checkNull(session.getMaximumUnits()));
        lblRegisteredUnits.setText(String.valueOf(getTotalRegisteredUnits(regCourses)));

        initTableWithCourses(tblCarried, carryOver.getCarriedCourses());

        if (regCourses.getRegisteredCourses().size() > 0) {
            initTableWithCourses(tblRegistered, regCourses.getRegisteredCourses());
        } else {
            initTableNoData(tblRegistered);
        }
    }

    private void initRegistrationPanel() {
        String approved = "Approved", unapproved = "Not Approved", notStarted = "Not Started", started = "Started", finished = "Finished", pending = "Pending",
                awaiting = "Awaiting Approval", yes = "Yes", no = "No";
        lblAdmin.setText(student.isRegistrationAllowed() ? approved : unapproved);
        lblRegStatus.setText(student.isRegistrationAllowed() ? (student.isCourseAdvisorApproved() ? (student.isDeanApproved() ? finished : started) : pending) : notStarted);
        lblStuReg.setText(student.isStuRegistered()? ((!student.isCourseAdvisorApproved()) || (!student.isHODApproved()) || (!student.isDeanApproved())? awaiting : yes) : no);
        lblHOD.setText(student.isHODApproved() ? approved : unapproved);
        lblDean.setText(student.isDeanApproved() ? approved : unapproved);
        lblCA.setText(student.isCourseAdvisorApproved() ? approved : unapproved);
        
    }

    /**
     * Initializes the carry overs table in registration panel
     */
    private void initTableWithCourses(JTable table, ArrayList<Course> courseList) {
        if (dummy) {
            initTableDummy(table);

        } else {
            initTable(table, carryOver.getCarriedCourses());
            initTable(table, courseList);
        }
    }

    private void initSelectedCoursesTable() {
        initTableNoData(tblSelectedCourses);
    }

    /**
     * Initialize course info dialog with course info
     *
     * @param course course object
     */
    private void initCourseInfo(Course course) {
        lblCourseCode.setText(course.getCourseCode());
        lblCourseLevel.setText(String.valueOf(course.getLevel()));
        lblCourseName.setText(course.getCourseName());
        lblCourseProgramme.setText(programme.getProgrammeName());
        lblCourseStatus.setText(course.getCourseStatus());
        lblCreditUnits.setText(String.valueOf(course.getCreditUnits()));
    }

    //Dummy Methods   
    /**
     * Dummy initialization for test
     *
     * @param course
     */
    private void initCourseInfoDummy() {
        lblCourseCode.setText("CMP 303");
        lblCourseLevel.setText("300");
        lblCourseName.setText("Introduction To Computer");
        lblCourseProgramme.setText("Computer Science");
        lblCourseStatus.setText("Compulsory");
        lblCreditUnits.setText("3");
    }

    //Custom methods

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCarryOver;
    private javax.swing.JButton btnAddNewCourse;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRemoveCourse;
    private javax.swing.JButton btnShowRegistration;
    private javax.swing.JDialog courseDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblBalanceFees;
    private javax.swing.JLabel lblCA;
    private javax.swing.JLabel lblCollege;
    private javax.swing.JLabel lblCourseCode;
    private javax.swing.JLabel lblCourseLevel;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseProgramme;
    private javax.swing.JLabel lblCourseStatus;
    private javax.swing.JLabel lblCreditUnits;
    private javax.swing.JLabel lblDean;
    private javax.swing.JLabel lblDept;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGpa;
    private javax.swing.JLabel lblHOD;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblMatricNo;
    private javax.swing.JLabel lblMaxUnits;
    private javax.swing.JLabel lblOriginalFees;
    private javax.swing.JLabel lblOriginalFees1;
    private javax.swing.JLabel lblOriginalFees2;
    private javax.swing.JLabel lblOriginalFees3;
    private javax.swing.JLabel lblPaidFees;
    private javax.swing.JLabel lblPassport;
    private javax.swing.JLabel lblProgramme;
    private javax.swing.JLabel lblRegStatus;
    private javax.swing.JLabel lblRegisteredUnits;
    private javax.swing.JLabel lblReportHeader;
    private javax.swing.JLabel lblReportHeader1;
    private javax.swing.JLabel lblReportHeader2;
    private javax.swing.JLabel lblReportHeader3;
    private javax.swing.JLabel lblReportHeader4;
    private javax.swing.JLabel lblReportHeader5;
    private javax.swing.JLabel lblStuReg;
    private javax.swing.JMenuItem menuChangePassword;
    private javax.swing.JPanel panelCourseDetails;
    private javax.swing.JPanel panelFinance;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JPanel panelRegistration;
    private javax.swing.JPanel panelReport;
    private javax.swing.JPanel panelShowDetails;
    private javax.swing.JSeparator separator;
    private javax.swing.JSeparator separator1;
    private javax.swing.JTabbedPane tabStudent;
    private javax.swing.JTable tblCarried;
    private javax.swing.JTable tblCarryOver;
    private javax.swing.JTable tblNewCourses;
    private javax.swing.JTable tblRegistered;
    private javax.swing.JTable tblSelectedCourses;
    // End of variables declaration//GEN-END:variables
}
